---

version: '3'

tasks:
  build:
    desc: Build all code
    cmds:
      - go build ./...
    silent: true

  test:
    desc: Run all tests
    cmds:
      - go test -shuffle on -coverprofile coverage.out ./...
    silent: true

  test-debug:
    desc: Run all tests with verbose output
    env:
      SOCKETIO_LOG_LEVEL: DEBUG
    cmds:
      - go test -v -shuffle on ./...
    silent: true

  test-e2e:
    desc: Run end-to-end tests
    env:
      E2E_TEST: "true"
    cmds:
      - go test -v -shuffle on -coverprofile coverage.out -timeout 120s ./...
    silent: true

  test-e2e-coverage:
    desc: Show coverage report for existing coverage.out or run end-to-end tests and generate coverage report
    env:
      E2E_TEST: "true"
    cmds:
      - |
        if [ ! -f "coverage.out" ]; then
          go test -v -shuffle on -coverprofile coverage.out -timeout 120s ./...
        fi
      - go tool cover -func=coverage.out | sort -k3 -rn
    silent: true

  lint:
    desc: Lint all code
    cmds:
      - golangci-lint run
    silent: true

  fmt:
    dsc: Format code using gofumpt
    cmds:
      - gofumpt -w .
    silent: true

  clean:
    desc: Clean temporary files
    cmds:
      - rm -f coverage.out
    silent: true
