---

version: '3'

tasks:
  build:
    desc: Build all code
    cmds:
      - go build ./...
    silent: true

  test:
    desc: Run all tests
    cmds:
      - go test -shuffle on ./...
    silent: true

  test-debug:
    desc: Run all tests with verbose output
    env:
      SOCKETIO_LOG_LEVEL: DEBUG
    cmds:
      - go test -v -shuffle on ./...
    silent: true

  test-e2e:
    desc: Run end-to-end tests
    env:
      E2E_TEST: "true"
    cmds:
      - go test -v -shuffle on -timeout 120s ./...
    silent: true

  lint:
    desc: Lint all code
    cmds:
      - golangci-lint run
    silent: true

  fmt:
    dsc: Format code using gofumpt
    cmds:
      - gofumpt -w .
    silent: true
